stages:
  - sync_to_github

sync_to_github:
  stage: sync_to_github
  script:
    - git remote add github https://$CI_GITHUB_TOKEN@github.com/samcolumbusbridge/bridge-mgmt-system.git
    - git push github main
  only:
    - main
