stages:
  - sync_to_github

sync_to_github:
  stage: sync_to_github
  script:
    - git checkout main # Ensure the main branch is checked out
    - git remote add github https://$CICD_GITHUB_TOKEN@github.com/sammmtobin/bridge-mgmt-system.git
    - git push github main
  only:
    - main
